services:
  go-revass-app-test:
    container_name: revass-app-test
    build:
      context: .
      dockerfile: tests/Dockerfile.app
    depends_on:
      postgres_test:
        condition: service_healthy
    env_file:
      - ./tests/.env.testing
    hostname: ${APP_HOST}
    networks:
      - testnet

  go-test:
    container_name: go-test
    build:
      context: .
      dockerfile: tests/Dockerfile.testing
    depends_on:
      - go-revass-app-test
    env_file:
      - ./tests/.env.testing
    networks:
      - testnet

  postgres_test:
    image: postgres:latest
    container_name: revass-test-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    hostname: testdb
    networks:
      - testnet
    volumes:
      - test-pgdata:/var/lib/postgresql/data/pgdata
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  test-pgdata:
    name: "revass-test-pg-data"

networks:
  testnet:
    driver: bridge